version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - dyron-network

  backend:
    build: ./backend
    image: delbertkimbi/dyron-backend:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - dyron-network

  frontend:
    build: ./dyron-frontend
    image: delbertkimbi/dyron-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dyron-network

volumes:
  mysql_data:

networks:
  dyron-network:
    driver: bridge 